# Generated by Django 5.2.7 on 2025-10-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('contato', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.CharField(default='agendado', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('duracao', models.IntegerField(default=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.patient')),
            ],
        ),
    ]
