# Generated by Django 5.2.7 on 2025-10-22 15:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('residencial', 'Telefone Residencial'), ('trabalho', 'Telefone Trabalho'), ('outro', 'Outro')], max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contato',
        ),
        migrations.AddField(
            model_name='patient',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(default='99999999999', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter exatamente 11 dígitos numéricos', regex='^\\d{11}$')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('remarcado', 'Remarcado'), ('nao_compareceu', 'Não Compareceu')], default='agendado', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='api.address'),
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('problemas_saude', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('cirurgias', models.TextField(blank=True, null=True)),
                ('ultima_consulta_dentista', models.DateField(blank=True, null=True)),
                ('motivo_ultima_consulta', models.CharField(blank=True, max_length=255, null=True)),
                ('experiencia_tratamento', models.TextField(blank=True, null=True)),
                ('fumante', models.BooleanField(default=False)),
                ('alcool', models.BooleanField(default=False)),
                ('frequencia_escovacao', models.CharField(blank=True, max_length=50, null=True)),
                ('usa_fio_dental', models.BooleanField(default=False)),
                ('sensibilidade_dental', models.BooleanField(default=False)),
                ('sangramento_gengival', models.BooleanField(default=False)),
                ('ranger_dentes', models.BooleanField(default=False)),
                ('dores_articulacao', models.BooleanField(default=False)),
                ('gestante', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('hipertensao', models.BooleanField(default=False)),
                ('problemas_cardiacos', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='api.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='contatos',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='api.contact'),
        ),
    ]
